project:
  type: website
  title: "just-enough-python"
  output-dir: docs/

website:
  repo-url: https://github.com/SchlossLab/just-enough-python/
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.html
    right:
      - icon: github
        href: https://github.com/SchlossLab/just-enough-python/

execute:
  freeze: auto
title-block-banner: true
title-block-style: default
author: "[Kelly Sovacool](https://sovacool.dev)"
date-format: iso
css: custom.css
toc: true
toc-depth: 5
theme: default
format:
  html:
    code-line-numbers: true
    code-link: true